del image.c
image2c blank.bmp            image.c
image2c blank_a.bmp          image.c
image2c blank_sn.bmp         image.c
image2c blank_sp.bmp         image.c
image2c charge.bmp           image.c
image2c charge1.bmp          image.c
image2c charge2.bmp          image.c
image2c connect1.bmp         image.c
image2c connect1_a.bmp       image.c
image2c discharge.bmp        image.c
image2c discharge1.bmp       image.c
image2c discharge2.bmp       image.c
image2c disconnect1.bmp      image.c
image2c disconnect1_a.bmp    image.c
image2c exit_foc.bmp         image.c
image2c exit_nor.bmp         image.c
image2c Export.bmp           image.c
image2c Export_a.bmp         image.c
image2c ground.bmp           image.c
image2c hasbat.bmp           image.c
image2c import.bmp           image.c
image2c import_a.bmp         image.c
image2c max_focu.bmp         image.c
image2c max_norm.bmp         image.c
image2c min_focu.bmp         image.c
image2c min_norm.bmp         image.c
image2c nobat.bmp            image.c
image2c option1.bmp          image.c
image2c option1_a.bmp        image.c
image2c Record1.bmp          image.c
image2c Record1_a.bmp        image.c
image2c Record2.bmp          image.c
image2c Record2_a.bmp        image.c
image2c recycle.bmp          image.c
image2c res_focu.bmp         image.c
image2c res_norm.bmp         image.c
image2c tim_a.bmp            image.c
image2c tim_b.bmp            image.c
image2c vol_a.bmp            image.c
image2c vol_b.bmp            image.c
image2c titletop.bmp         image.c
pause